# Generated by Django 4.0.6 on 2022-07-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donnee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='images')),
            ],
            options={
                'verbose_name': ('Donnee',),
                'verbose_name_plural': 'Donnees',
            },
        ),
    ]
