# Generated by Django 4.0.5 on 2022-07-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prof',
            name='profil',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
