# Generated by Django 4.0.5 on 2022-07-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_prof_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='profil',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
