# Generated by Django 4.0.5 on 2022-06-25 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produits',
            options={'verbose_name': ('Produit',), 'verbose_name_plural': 'Produits'},
        ),
    ]
