# Generated by Django 4.0.5 on 2022-06-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_produits_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='produits',
            name='stock',
            field=models.DecimalField(decimal_places=2, max_digits=65, null=True),
        ),
    ]
