# Generated by Django 4.0.5 on 2022-06-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_produits_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produits',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
