# Generated by Django 4.0.5 on 2022-06-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_produits_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produits',
            name='prix',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=60),
        ),
        migrations.AlterField(
            model_name='produits',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
