# Generated by Django 4.0.5 on 2022-06-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_produits_prix_alter_produits_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produits',
            name='prix',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=65),
        ),
    ]
