# Generated by Django 4.0.5 on 2022-06-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_produits_prix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produits',
            name='prix',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
