# Generated by Django 4.0.5 on 2022-07-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_produits_prix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produits',
            name='image',
            field=models.FileField(blank=True, upload_to='images'),
        ),
    ]
