# Generated by Django 3.1.6 on 2022-07-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_produits_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150)),
                ('ecole', models.CharField(max_length=150)),
                ('salaire', models.IntegerField(blank=True, null=True)),
                ('profil', models.ImageField(blank=True, upload_to='images_panel')),
            ],
            options={
                'verbose_name': ('Panel',),
                'verbose_name_plural': 'Panels',
            },
        ),
    ]
