# Generated by Django 3.1.6 on 2022-07-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_panel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('matiere', models.CharField(max_length=150)),
                ('profil', models.ImageField(blank=True, upload_to='images_panel')),
            ],
            options={
                'verbose_name': ('Prof',),
                'verbose_name_plural': 'Profs',
            },
        ),
    ]
