# Generated by Django 3.1.6 on 2022-07-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_prof'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panel',
            old_name='salaire',
            new_name='prenom',
        ),
        migrations.AddField(
            model_name='prof',
            name='salaire',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
