# Generated by Django 3.1.6 on 2022-07-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20220702_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='prenom',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
