# Generated by Django 3.1.6 on 2022-07-03 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20220702_1802'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Panel',
        ),
        migrations.DeleteModel(
            name='Prof',
        ),
    ]
